### ISSUE TITLE
Function Examples end as Sub

### ISSUE THREAD

**Issue by ColmBhandal** [VBA-tools/vba-test#31]
There are at least two code examples in this project which are functions but end with "End Sub":

- In Readme.md the function "Function AddTests() As TestSuite"
- In the TDD example, the function "Public Function Specs() As SpecSuite"

This is a trivial issue, I know. It's a documentation issue really rather than a source code issue. But since the fix is also trivial I figured I might as well raise it.

Fix: Change "End Sub" to "End Function"

P.s. Thanks for the amazing test harness!

**Comment by cxw42** [comment]
Looks like #32 took care of readme.md, and I just edited the wiki page :) .  I believe this can be closed.

**Comment by timhall** [comment]
👍
